### ISSUE TITLE
Where is the screenshot taken?

### ISSUE THREAD

**Issue by DorofD** [impshum/Flask-Screenshot#1]
Hello, my friend! 
Please explain one thing to me. The function that actually takes a screenshot is called on the server side, while the route function does not accept any data. If we enter the application not from the same machine on which the application is deployed, a screenshot of the server screen is taken at the click of the button, it is just black, there is nothing on it. Please share what was the idea of combining pyscreenshot and flask?

P.s. Sorry, didn't read readme first)) My bad

**Comment by impshum** [comment]
OK.
